//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerdemographic
    {
        public customerdemographic()
        {
            this.customers = new HashSet<customer>();
        }
    
        public string CustomerTypeID { get; set; }
        public string CustomerDesc { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
