//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_Project.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<customerdemographic> customerdemographics { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<order_detail> order_details { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<shipper> shippers { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<territory> territories { get; set; }
    }
}
